const assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
(async()=>{const browser=await chromium.launch({headless:true,channel:'msedge'});try{
const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto((process.env.FAIR_VALUE_TEST_URL||'http://127.0.0.1:5094')+'/fair-value-observation');
const ready=()=>page.waitForFunction(()=>!document.querySelector('#apply').disabled && document.querySelector('#bonds a.bond'));
await ready();assert.match(await page.locator('#latest-date').innerText(),/2026-09-16/);
assert.equal(await page.locator('#cards,#kind,#version').count(),0);assert.equal(await page.locator('#research').getAttribute('open'),null);
const link=page.locator('a.bond').first();assert.equal(await link.getAttribute('target'),'_blank');assert.match(await link.getAttribute('href'),/^\/bond-detail\?code=/);
await page.screenshot({path:'.test_runtime/fair_value_desktop.png'});
await page.click('#older');await ready();assert.match(await page.locator('#count').innerText(),/2026-09-15/);
assert.ok(await page.evaluate(()=>{document.getElementById('older').click();return document.getElementById('results').classList.contains('loading')&&document.getElementById('count').textContent==='正在读取数据…'&&document.getElementById('loading').offsetParent!==null;}),'切换日期应立即显示读取进度');
await ready();assert.equal(await page.evaluate(()=>document.getElementById('results').classList.contains('loading')),false,'读取完成后进度应消失');
await page.click('#ms_rating .ms-display');await page.locator('#drop-ms_rating input[type="checkbox"]').first().check();
assert.match(await page.locator('#ms_rating .ms-display').innerText(),/AA\+/);assert.equal(await page.locator('#ms_rating .ms-display .ms-tag').count(),1);
await page.click('#apply');await ready();assert.equal(await page.locator('a.bond').count(),2);assert.equal(await page.locator('#bonds td:nth-child(3)').filter({hasText:'AAA'}).count(),0);
await page.click('#ms_rating .ms-tag-x');assert.match(await page.locator('#ms_rating .ms-display').innerText(),/全部/);await page.click('#apply');await ready();assert.equal(await page.locator('a.bond').count(),3);
await page.selectOption('#date','8');await ready();
await page.locator('[data-prediction]:not([data-rates])').first().click();await page.waitForSelector('#chart canvas');
assert.match(await page.locator('#detail-summary').innerText(),/方向正确|方向相反|无变化/);
await page.click('[data-chart="yield_value"]');await page.locator('#conditions summary').click();assert.match(await page.locator('#rate-note').innerText(),/历史回看/);
await page.screenshot({path:'.test_runtime/fair_value_drawer.png'});await page.click('#close-detail');
const code=new URL(await page.locator('a.bond').first().getAttribute('href'),page.url()).searchParams.get('code');
await page.fill('#search',code);await page.click('#apply');await ready();assert.equal(await page.locator('a.bond').count(),1);
const csv=await page.request.get(new URL(await page.locator('#export').getAttribute('href'),page.url()).href);assert.equal(csv.status(),200);assert.equal((await csv.text()).trim().split('\n').length,2);
await page.click('#reset');await ready();await page.click('[data-direction="widen"]');await ready();assert.ok((await page.locator('#bonds').innerText()).includes('收益率偏低'));
await page.selectOption('#horizon','10');await ready();assert.match(await page.locator('#bonds').innerText(),/待兑现/);
await page.setViewportSize({width:390,height:844});await page.screenshot({path:'.test_runtime/fair_value_mobile.png'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
await page.click('#toggle-filters');assert.ok(await page.locator('#search').isVisible());assert.deepEqual(errors,[]);
console.log('UI passed: date history, loading indicator, multiselect tags, judgments, drawer, rate explanations, search/export parity, pending horizon, mobile, console.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
